In [2]:
import numpy as np
import matplotlib.pyplot as plt

import statsmodels.api as sm

In [4]:
nsample = 8
sig = 0.25
x1 = np.linspace(0, 20, nsample)
X = np.column_stack((x1, np.sin(x1), (x1-5)**2))
X = sm.add_constant(X)
beta = [5., 0.5, 0.5, -0.02]
y_true = np.dot(X, beta)
y = y_true + sig * np.random.normal(size=nsample)

In [5]:
print(X)

[[  1.           0.           0.          25.        ]
 [  1.           2.85714286   0.2806294    4.59183673]
 [  1.           5.71428571  -0.53870529   0.51020408]
 [  1.           8.57142857   0.75348673  12.75510204]
 [  1.          11.42857143  -0.90771225  41.32653061]
 [  1.          14.28571429   0.98898712  86.2244898 ]
 [  1.          17.14285714  -0.99077947 147.44897959]
 [  1.          20.           0.91294525 225.        ]]


In [6]:
np.column_stack((x1, np.sin(x1), (x1-5)**2))

array([[  0.        ,   0.        ,  25.        ],
       [  2.85714286,   0.2806294 ,   4.59183673],
       [  5.71428571,  -0.53870529,   0.51020408],
       [  8.57142857,   0.75348673,  12.75510204],
       [ 11.42857143,  -0.90771225,  41.32653061],
       [ 14.28571429,   0.98898712,  86.2244898 ],
       [ 17.14285714,  -0.99077947, 147.44897959],
       [ 20.        ,   0.91294525, 225.        ]])