# Introducción a
<img src="https://raw.githubusercontent.com/fhernanb/fhernanb.github.io/master/docs/logo_tensor_flow.png" alt="drawing" width="200"/>

In [1]:
import tensorflow as tf

## Creación de constantes

In [2]:
c1 = tf.constant(value=3.0, dtype=tf.float32, name="mi_constante1")
c2 = tf.constant(value=5, dtype=tf.float32, name="mi_constante2")

print("Para explorar las constantes")
print(c1)
print(c2)
print("\n")

# Creando la sesión
sess = tf.Session()

print("Para evaluar y ver lo que hay dentro de las constantes")
print(sess.run(c1))
print(sess.run(c2))

Para explorar las constantes
Tensor("mi_constante1:0", shape=(), dtype=float32)
Tensor("mi_constante2:0", shape=(), dtype=float32)


Para evaluar y ver lo que hay dentro de las constantes
3.0
5.0


## Creación de tensores

In [3]:
# Constant 1-D Tensor populated with value list.
tensor1 = tf.constant([1, 2, 3, 4, 5, 6], name="mi_tensor1")

# Constant 1-D Tensor populated with value list.
tensor2 = tf.constant([1, 2, 3, 4, 5, 6], shape=(2,3), name="mi_tensor2")

# Constant 2-D tensor populated with scalar value -1.
tensor3 = tf.constant(-1.0, shape=[2, 3], name="mi_tensor3") 

print("Para explorar los tensores")
print(tensor1)
print(tensor2)
print(tensor3)
print("\n")

print("Para evaluar y ver lo que hay dentro de los tensores")
print(sess.run(tensor1), "\n")
print(sess.run(tensor2), "\n")
print(sess.run(tensor3), "\n")

Para explorar los tensores
Tensor("mi_tensor1:0", shape=(6,), dtype=int32)
Tensor("mi_tensor2:0", shape=(2, 3), dtype=int32)
Tensor("mi_tensor3:0", shape=(2, 3), dtype=float32)


Para evaluar y ver lo que hay dentro de los tensores
[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[[-1. -1. -1.]
 [-1. -1. -1.]] 



# Operaciones básicas

## Suma
Para sumar tensores se usa el método `.add`, más detalles [aquí](https://www.tensorflow.org/api_docs/python/tf/math/add).

In [5]:
c3 = tf.add(x=c1, y=c2, name="mi_constate3")
print(c3)
print(sess.run(c3))

Tensor("mi_constate3_1:0", shape=(), dtype=float32)
8.0


In [6]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

Tensor("Add:0", shape=(), dtype=int32)
Tensor("Add_1:0", shape=(2,), dtype=int32)
Tensor("Square:0", shape=(), dtype=int32)
Tensor("Sum:0", shape=(), dtype=int32)
Tensor("add_2:0", shape=(), dtype=int32)
