# Operaciones con matrices
<img src="https://raw.githubusercontent.com/fhernanb/fhernanb.github.io/master/my_docs/logo_unal_color.png" alt="drawing" width="200"/>

In [1]:
import numpy as np

## Creación de vectores y matrices

Vamos a crear tres vectores, el primero un vector columna con los números 2 y 3; el segundo un vector fila con los números -1 y 5; el tercero un vector columna con los números 6, 4.

In [2]:
v1 = np.array([[2],
              [3]])

v2 = np.array([[-1, 5]])

v3 = np.array([[6, 4]])
v3 = np.transpose(v3)

print("El vector v1 es: \n", v1)
print("El vector v2 es: \n", v2)
print("El vector v3 es: \n", v3)

print("Las dimensiones de v1 son: \n", v1.shape)
print("Las dimensiones de v2 son: \n", v2.shape)
print("Las dimensiones de v2 son: \n", v3.shape)

El vector v1 es: 
 [[2]
 [3]]
El vector v2 es: 
 [[-1  5]]
El vector v3 es: 
 [[6]
 [4]]
Las dimensiones de v1 son: 
 (2, 1)
Las dimensiones de v2 son: 
 (1, 2)
Las dimensiones de v2 son: 
 (2, 1)


<div class="alert alert-warning">
  <strong>Nota</strong> Para crear el vector columna se puede construirlo primero como vector fila y luego transpornerlo.
</div>

Vamos a crear las matrices $M$ y $S$.

$
M = \begin{pmatrix}
1 & 2  \\
3 & 5  
\end{pmatrix} $

$
S = \begin{pmatrix}
3 & 2 & 4  \\
5 & 6 & 1
\end{pmatrix} $

In [3]:
M = np.array([[1, 2],
              [3, 5]])

print("La matriz M es: \n", M)

print("Las dimensiones de M son: \n", M.shape)

S = np.array([[3, 2 , 4],
              [5, 6, 1]])

print("La matriz M es: \n", S)

print("Las dimensiones de M son: \n", S.shape)

La matriz M es: 
 [[1 2]
 [3 5]]
Las dimensiones de M son: 
 (2, 2)
La matriz M es: 
 [[3 2 4]
 [5 6 1]]
Las dimensiones de M son: 
 (2, 3)


## Operaciones con vectores y matrices

In [4]:
v1 + v3 # suma de vectores

array([[8],
       [7]])

In [5]:
2 * v1 + 3 * v3 # combinacion lineal de vectores

array([[22],
       [18]])

In [6]:
print(v1)
print(v3.T)
np.dot(v1, v3.T) # producto matricial de vectores

[[2]
 [3]]
[[6 4]]


array([[12,  8],
       [18, 12]])

In [7]:
v1 * v3 # producto elemento a elemento

array([[12],
       [12]])

In [8]:
np.matmul(M, S) # producto matricial

array([[13, 14,  6],
       [34, 36, 17]])

In [9]:
np.matmul(S.T, M) # producto matricial

array([[18, 31],
       [20, 34],
       [ 7, 13]])